source:
  - ./Downloads

extensions:
  images:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .webp
    - .tiff
    - .svg
    - .heic
    - .avif
    - .psd
    - .ai

  video:
    - .mp4
    - .mkv
    - .mov
    - .avi
    - .wmv
    - .flv
    - .webm
    - .m4v
    - .mpg
    - .mpeg

  audio:
    - .mp3
    - .wav
    - .flac
    - .ogg
    - .m4a
    - .aac
    - .wma
    - .opus

  documents:
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    - .odt
    - .txt
    - .rtf
    - .md
    - .epub
    - .fb2
    - .djvu

folders:
  images:
    - ./Pictures
  
  audio:
    - ./Music
  
  video:
    - ./Videos
  
  documents:
    - ./Documents
